"""
Process Realistic News Dataset with FinBERT

Reads realistic news generated by generate_realistic_news.py
and runs FinBERT sentiment analysis on all articles.

Output: CSV files with sentiment scores for each trading day.
"""

import sys
import os
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

from sentiment.models.finbert_sentiment import FinBERTSentiment


def process_realistic_news_dataset(news_dir: str, output_dir: str):
    """
    Process all realistic news CSV files with FinBERT.

    Args:
        news_dir: Directory containing realistic news CSV files
        output_dir: Output directory for sentiment results
    """
    print("=" * 70)
    print("FINBERT SENTIMENT ANALYSIS - REALISTIC NEWS DATASET")
    print("=" * 70)

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Initialize FinBERT
    print("\n[+] Initializing FinBERT model...")
    try:
        analyzer = FinBERTSentiment()
        print("[SUCCESS] FinBERT model loaded successfully!")
    except Exception as e:
        print(f"[ERROR] Error loading FinBERT: {e}")
        print("[INFO] Please install dependencies: pip install transformers torch")
        return

    # Get all news CSV files
    news_files = sorted(Path(news_dir).glob("vn30_news_*.csv"))
    print(f"\n[+] Found {len(news_files)} news files to process")
    print("=" * 70)

    # Process each file
    all_results = []

    for news_file in news_files:
        date_str = news_file.stem.replace("vn30_news_", "")
        print(f"\n[{date_str}] Processing news file...")

        # Read news data
        df = pd.read_csv(news_file)
        print(f"  [INFO] Loaded {len(df)} articles")

        # Group by ticker
        grouped = df.groupby('ticker')

        for ticker, group in grouped:
            print(f"\n  [{ticker}] {len(group)} articles")

            ticker_results = []
            sentiment_scores = []

            for idx, row in group.iterrows():
                try:
                    # Analyze sentiment
                    result = analyzer.analyze_text(row['news_text'])

                    # Store result
                    ticker_results.append({
                        'date': row['date'],
                        'ticker': ticker,
                        'article_id': row['article_id'],
                        'news_preview': row['news_text'][:80] + "...",
                        'sentiment_score': result.sentiment_score,
                        'sentiment_label': result.sentiment_label,
                        'positive_score': result.positive_score,
                        'negative_score': result.negative_score,
                        'neutral_score': result.neutral_score,
                        'model_version': 'finbert_v1.0',
                        'processed_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                    })

                    sentiment_scores.append(result.sentiment_score)

                except Exception as e:
                    print(f"    [ERROR] Error analyzing {row['article_id']}: {e}")

            # Calculate aggregate sentiment for this ticker on this day
            if sentiment_scores:
                avg_sentiment = np.mean(sentiment_scores)
                avg_label = "Positive" if avg_sentiment > 0.2 else "Negative" if avg_sentiment < -0.2 else "Neutral"

                print(f"    [SUMMARY] Avg Score: {avg_sentiment:+.3f} ({avg_label})")

            all_results.extend(ticker_results)

    # Save combined results
    if all_results:
        print("\n" + "=" * 70)
        print("Saving sentiment analysis results...")

        # Create combined DataFrame
        combined_df = pd.DataFrame(all_results)

        # Reorder columns
        columns = ['date', 'ticker', 'article_id', 'sentiment_score', 'sentiment_label',
                  'positive_score', 'negative_score', 'neutral_score', 'news_preview',
                  'model_version', 'processed_at']
        combined_df = combined_df[columns]

        # Sort by date and ticker
        combined_df = combined_df.sort_values(['date', 'ticker', 'article_id'])

        # Save combined CSV
        combined_file = os.path.join(output_dir, "vn30_sentiment_combined.csv")
        combined_df.to_csv(combined_file, index=False, encoding='utf-8')
        print(f"  [OK] Combined results: {len(combined_df)} articles")
        print(f"  [FILE] {combined_file}")

        # Save per-day files
        for date, date_group in combined_df.groupby('date'):
            date_file = os.path.join(output_dir, f"vn30_sentiment_{date}.csv")
            date_group.to_csv(date_file, index=False, encoding='utf-8')
            print(f"  [OK] {date}: {len(date_group)} articles")

        # Save per-ticker daily files (for time series analysis)
        print("\n  [INFO] Creating per-ticker daily sentiment files...")
        for ticker in combined_df['ticker'].unique():
            ticker_data = combined_df[combined_df['ticker'] == ticker].copy()

            # Group by date and calculate daily aggregate
            daily_agg = []
            for date, date_group in ticker_data.groupby('date'):
                if len(date_group) > 0:
                    daily_agg.append({
                        'date': date,
                        'ticker': ticker,
                        'num_articles': len(date_group),
                        'avg_sentiment_score': date_group['sentiment_score'].mean(),
                        'avg_positive_score': date_group['positive_score'].mean(),
                        'avg_negative_score': date_group['negative_score'].mean(),
                        'avg_neutral_score': date_group['neutral_score'].mean(),
                        'sentiment_std': date_group['sentiment_score'].std(),
                        'min_sentiment': date_group['sentiment_score'].min(),
                        'max_sentiment': date_group['sentiment_score'].max()
                    })

            if daily_agg:
                ticker_daily_df = pd.DataFrame(daily_agg)
                ticker_daily_file = os.path.join(output_dir, f"{ticker}_sentiment_daily.csv")
                ticker_daily_df.to_csv(ticker_daily_file, index=False, encoding='utf-8')

        print(f"\n[SUCCESS] All sentiment results saved!")
        print(f"[DIR] {output_dir}")

        # Print summary statistics
        print("\n" + "=" * 70)
        print("SUMMARY STATISTICS")
        print("=" * 70)

        print(f"\nTotal Articles Analyzed: {len(combined_df)}")
        print(f"Date Range: {combined_df['date'].min()} to {combined_df['date'].max()}")
        print(f"Stocks Covered: {len(combined_df['ticker'].unique())}")

        print(f"\nSentiment Distribution:")
        sentiment_counts = combined_df['sentiment_label'].value_counts()
        for label, count in sentiment_counts.items():
            pct = count / len(combined_df) * 100
            print(f"  {label}: {count} ({pct:.1f}%)")

        print(f"\nPer-Stock Average Sentiment:")
        for ticker in sorted(combined_df['ticker'].unique()):
            ticker_data = combined_df[combined_df['ticker'] == ticker]
            avg_score = ticker_data['sentiment_score'].mean()
            print(f"  {ticker}: {avg_score:+.3f}")

        print(f"\nOverall Market Sentiment: {combined_df['sentiment_score'].mean():+.3f}")
        print("=" * 70)


def main():
    """Main execution"""
    news_dir = "D:/bmad-projects/stock_vol_prediction01/data/raw/vn30_sentiment/news"
    output_dir = "D:/bmad-projects/stock_vol_prediction01/data/processed/vn30_sentiment/daily"

    process_realistic_news_dataset(news_dir, output_dir)

    print("\n" + "=" * 70)
    print("REALISTIC NEWS SENTIMENT ANALYSIS COMPLETED!")
    print("=" * 70)
    print("\n[SUCCESS] FinBERT sentiment analysis completed on realistic news dataset")
    print("[SUCCESS] Results saved to processed data directory")
    print("[INFO] This dataset uses realistic news patterns (not web-scraped)")
    print("[INFO] Avoids legal issues while providing educational value")
    print("\n[CHECK] Check results in: data/processed/vn30_sentiment/daily/")
    print("[NEXT] Ready for HAR sentiment feature engineering!")
    print("=" * 70)


if __name__ == "__main__":
    main()
