"""THE single authoritative generator for the paper's result tables (external review F-03).

Reads the canonical result.json artifacts and emits markdown + LaTeX rows with an explicit provenance header
(SHA-256 of every input file). It is the ONE place that decides which stored field is authoritative:

  * LEARNED models (LSTM, LSTM+GAT variants)  -> the MEAN of seed-level metrics in ``metrics_per_seed``
    (+ its std), NEVER the seed-ensemble metric in ``metrics`` (a distinct, generally-lower quantity).
  * DETERMINISTIC models (HAR, HAR-X, GARCH)  -> ``metrics`` (there is no seed dimension).

Fail-loud: if a learned model lacks ``metrics_per_seed`` the generator RAISES rather than silently falling
back to the ensemble field -- this is the anti-drift guard the review asked for (``build_report.py`` reading
legacy ``metrics`` for learned models was the provenance risk). Legacy report/paper artifacts are NOT
authoritative; regenerate from here.

CLI: ``python build_final_tables.py [--results-root DIR] [--out DIR]`` -> writes final_tables.md + .tex.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

LEARNED = ("LSTM", "LSTM_wGAT_vol2pk", "LSTM_wGAT_corr")
DETERMINISTIC = ("HAR", "HAR-X", "GARCH")
METRICS = ("mse", "rmse", "mae", "qlike", "r2")
PANELS = ("vn30", "vn100", "hose", "hnx", "sp500")
HORIZONS = (1, 5, 10, 22)


def authoritative_cell(res: dict, model: str, metric: str) -> dict | None:
    """Return ``{"value": float, "std": float|None, "source": "per_seed"|"ensemble"}`` for one cell, applying
    the authoritative rule. Returns ``None`` if the model is simply absent (e.g. GARCH not yet added).
    Raises ``KeyError`` if a LEARNED model is present in ``metrics`` but missing from ``metrics_per_seed``
    (would otherwise silently report the wrong ensemble number)."""
    if model in LEARNED:
        ps = res.get("metrics_per_seed", {})
        if model not in ps:
            if model in res.get("metrics", {}):
                raise KeyError(f"learned model '{model}' has ensemble metrics but NO metrics_per_seed "
                               "(refusing to report the ensemble value -- would misreport the paper number)")
            return None
        cell = ps[model]
        if metric not in cell:
            return None
        return {"value": float(cell[metric]), "std": (float(cell[metric + "_std"]) if metric + "_std" in cell else None),
                "source": "per_seed"}
    m = res.get("metrics", {})
    if model not in m or metric not in m[model]:
        return None
    return {"value": float(m[model][metric]), "std": None, "source": "ensemble"}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def build_tables(results_root: Path, panels=PANELS, horizons=HORIZONS) -> dict:
    """Read every ``<panel>_h<h>/result.json`` under ``results_root`` and return a structured table plus a
    provenance map ``{relpath: sha256}``. Missing cells are recorded as ``None``."""
    results_root = Path(results_root)
    rows = []
    provenance = {}
    for panel in panels:
        for h in horizons:
            rp = results_root / f"{panel}_h{h}" / "result.json"
            if not rp.exists():
                continue
            provenance[f"{panel}_h{h}"] = _sha256(rp)
            res = json.loads(rp.read_text(encoding="utf-8"))
            for model in DETERMINISTIC[:2] + LEARNED[:2] + ("GARCH",):   # HAR, HAR-X, LSTM, LSTM+GAT, GARCH
                cells = {mt: authoritative_cell(res, model, mt) for mt in METRICS}
                if all(v is None for v in cells.values()):
                    continue
                rows.append({"panel": panel, "horizon": h, "model": model, "cells": cells})
    return {"rows": rows, "provenance": provenance}


def _fmt(cell: dict | None) -> str:
    if cell is None:
        return "-"
    if cell["std"] is not None:
        return f"{cell['value']:.4f} ({cell['std']:.3f})"
    return f"{cell['value']:.4f}"


def render_markdown(table: dict) -> str:
    lines = ["# Authoritative paper result tables (generated by scripts/paper/build_final_tables.py)",
             "", "Learned = per-seed mean (std); deterministic = ensemble metric. Do NOT hand-edit or quote "
             "legacy artifacts.", "",
             "## Provenance (SHA-256 of input result.json)", ""]
    for k in sorted(table["provenance"]):
        lines.append(f"- `{k}`: `{table['provenance'][k]}`")
    lines += ["", "## Results", "", "| panel | h | model | " + " | ".join(METRICS) + " |",
              "|" + "---|" * (3 + len(METRICS))]
    for r in table["rows"]:
        cells = " | ".join(_fmt(r["cells"][mt]) for mt in METRICS)
        lines.append(f"| {r['panel']} | {r['horizon']} | {r['model']} | {cells} |")
    return "\n".join(lines) + "\n"


def render_latex(table: dict) -> str:
    out = ["% generated by scripts/paper/build_final_tables.py -- authoritative; do not hand-edit"]
    for r in table["rows"]:
        cells = " & ".join(_fmt(r["cells"][mt]) for mt in METRICS)
        out.append(f"{r['panel']} & {r['horizon']} & {r['model']} & {cells} \\\\")
    return "\n".join(out) + "\n"


def main(argv=None):  # pragma: no cover - CLI entry driver
    import argparse
    ap = argparse.ArgumentParser()
    repo = Path(__file__).resolve().parents[2]
    ap.add_argument("--results-root", default=str(repo / "results" / "masked_rich_floor1e2"))
    ap.add_argument("--out", default=str(repo / "docs" / "paper" / "generated"))
    a = ap.parse_args(argv)
    table = build_tables(Path(a.results_root))
    out = Path(a.out); out.mkdir(parents=True, exist_ok=True)
    (out / "final_tables.md").write_text(render_markdown(table), encoding="utf-8")
    (out / "final_tables.tex").write_text(render_latex(table), encoding="utf-8")
    print(f"wrote {out/'final_tables.md'} and .tex ({len(table['rows'])} rows, "
          f"{len(table['provenance'])} panels)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
